spring:
    datasource:
        url: jdbc:postgreesql://localhost:5432/imageLite
        username: postgres
        password: postgres
    jpa: 
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        show-sql: true
    